name: Cleanup Old Package Versions

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'ecs-initial-image'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: true
      - name: Validate architectures exist without pulling
        run: |
          manifest=$(docker manifest inspect ghcr.io/k-kojima-yumemi/ecs-initial-image:latest)
          echo "$manifest" | jq -r '.manifests[].platform | select(.os=="linux") | "\(.os)/\(.architecture)"' | grep -E "(linux/amd64|linux/arm64)" | wc -l | grep -q "2"

